- name: "Malicious Software Removal Tool"
  tag: "scan_virus"
  cmd: ["mrt", "/q", "/f:y"] 
  timeout: 600

- name: "System File Checker"
  tag: "scan_sfc"
  cmd: ["sfc", "/scannow"]
  timeout: 1200

- name: "DISM Restore Health"
  tag: "scan_dism"
  cmd: ["DISM", "/Online", "/Cleanup-Image", "/RestoreHealth"]
  timeout: 1800
